// Lines for 07-data-and-integrations.pdf — the content block for
// the customer-support RAG fixture "Pulsar Analytics - Data Sources and Integrations".
// Re-render with `renderPdf` from this package; this file is
// pure data, no pdf-lib import.
export const lines: readonly string[] = [

    'Pulsar Analytics - Data Sources and Integrations',
    'Effective May 2026',
    '',
    '1. Supported data sources',
    'Pulsar connects to managed Postgres (Neon, Supabase, RDS),',
    'Snowflake, BigQuery, Databricks, Redshift, and uploaded CSV.',
    'Each connection is configured in Workspace > Data sources and',
    'can be tested from the same page.',
    '',
    '2. Refresh cadence',
    'Each data source has a refresh schedule. The default is every 1)',
    'hour for warehouse sources and every 15 minutes for Postgres',
    "replicas. Change the cadence from the data source's edit page.",
    'Schedules as fast as every 5 minutes are available on Business',
    'and Enterprise plans.',
    '',
    '3. Schema drift',
    'When a connected table adds, removes, or renames a column,',
    'Pulsar flags the dashboard with a yellow warning banner. Click the',
    'banner to view a diff and either accept the change (which updates',
    "the dashboard's query automatically) or pin the dashboard to",
    'the previous schema until you fix it manually.',
    '',
    '4. Stale data',
    'If a dashboard is showing older values than expected, the cause',
    'is almost always one of: (a) the warehouse has not received new',
    'rows since the last refresh; (b) the refresh schedule is set to',
    'daily instead of hourly; (c) the source credential has expired and',
    'the connection is in a failed state. Open Workspace > Data',
    'sources to inspect status and last-run timestamps.',
    '',
    '5. Webhooks and outbound events',
    'See the API reference for the full list of webhooks Pulsar',
    'emits. The most common for downstream automation are:',
    'dashboard.published, query.failed, datasource.health.degraded.',
    'All three are signed with HMAC-SHA256.',
    '',
    '6. Limits',
    'Per query: 10 000 rows returned, 60 second timeout, 1 GB scanned.',
    'Per dashboard: 50 tiles. Per workspace: 500 dashboards on Team,',
    'unlimited on Business and Enterprise.',
  
];
