// Lines for 04-billing-and-plans.pdf — the content block for
// the customer-support RAG fixture "Pulsar Analytics - Billing and Plans".
// Re-render with `renderPdf` from this package; this file is
// pure data, no pdf-lib import.
export const lines: readonly string[] = [

    'Pulsar Analytics - Billing and Plans',
    'Updated May 2026',
    '',
    '1. Plan tiers',
    'Pulsar offers four plan tiers:',
    '  Starter: free, up to 3 members, 1 GB data, 30-day history.',
    '  Team: USD 49 per member per month, unlimited dashboards, 1-year',
    'history, email support.',
    '  Business: USD 99 per member per month, SSO, audit log 365 days,',
    'SLA 99.9 percent, priority support.',
    '  Enterprise: custom pricing, custom roles, dedicated infra,',
    'SLA 99.99 percent, dedicated CSM.',
    '',
    '2. Invoices',
    'Invoices are issued on the first of each month for the previous',
    'month. Download them from Workspace > Billing > Invoices.',
    'Each invoice lists every line item, the unit price, and the',
    'applicable tax for your billing address.',
    '',
    '3. Payment methods',
    'Pulsar accepts Visa, Mastercard, American Express, and ACH',
    'direct debit. Enterprise customers can pay by wire transfer with',
    'net-30 terms. Add a payment method from Workspace > Billing >',
    'Payment method.',
    '',
    '4. Failed payments and dunning',
    'If a charge fails, Pulsar retries the card on day 3 and day 7,',
    'sending an email to the billing contact each time. On day 14',
    'the workspace is downgraded to read-only; on day 30 the workspace',
    'is suspended. Update the card to restore access immediately.',
    '',
    '5. Cancellation',
    'Cancel anytime from Workspace > Billing > Plan. The workspace',
    'remains active until the end of the current billing period. After',
    'cancellation, data is retained for 30 days and then permanently',
    'deleted. Download an export before cancelling if you need it.',
    '',
    '6. Plan changes',
    'Upgrades take effect immediately and are pro-rated. Downgrades',
    'take effect at the next billing date; the workspace keeps its',
    'current features until then.',
  
];
