// Lines for 06-troubleshooting.pdf — the content block for
// the customer-support RAG fixture "Pulsar Analytics - Troubleshooting Guide".
// Re-render with `renderPdf` from this package; this file is
// pure data, no pdf-lib import.
export const lines: readonly string[] = [

    'Pulsar Analytics - Troubleshooting Guide',
    'Version 1.8 - May 2026',
    '',
    '1. Common errors',
    'Dashboard shows "stale": the underlying data source has not',
    'refreshed. Open the dashboard, click the data-source name in the',
    'footer, and choose Refresh now. See the data-and-integrations',
    'guide for refresh cadence defaults.',
    '',
    'Query failed with 429: the workspace is rate-limited. Wait for',
    'the time indicated in the Retry-After header (usually 30 to 60',
    'seconds) and retry. If you repeatedly hit 429, contact support to',
    'raise your workspace quota.',
    '',
    'Sign-in loop: your session cookie is stale. Sign out from the',
    'account menu, then sign back in. If the loop persists, clear the',
    'browser cookies for app.pulsaranalytics.io and try again.',
    '',
    '2. Status page',
    'Live system status is at status.pulsaranalytics.io. Pulsar posts',
    'incidents, planned maintenance, and historical uptime there.',
    'Subscribe with email or Slack to receive notifications.',
    '',
    '3. Diagnostic info',
    'When you contact support, please include your workspace id',
    'found in Settings > General, your account email, the time of the',
    'issue (with timezone), and a screenshot of the error toast.',
    '',
    '4. Support contact',
    'Starter: community forum only.',
    'Team: email support, 1 business day response.',
    'Business: priority email, 4 business hour response.',
    'Enterprise: dedicated CSM, 1 business hour response, 24x7',
    'for severity 1 incidents.',
    '',
    '5. Reporting a security issue',
    'Email security@pulsaranalytics.io or use the in-app Report a',
    "security issue link from the help menu. Pulsar's security team",
    'acknowledges within 1 business hour and aims to remediate',
    'within 24 hours for high-severity findings.',
  
];
