// Lines for 05-account-and-security.pdf — the content block for
// the customer-support RAG fixture "Pulsar Analytics - Account and Security".
// Re-render with `renderPdf` from this package; this file is
// pure data, no pdf-lib import.
export const lines: readonly string[] = [

    'Pulsar Analytics - Account and Security',
    'Member-facing - Effective May 2026',
    '',
    '1. Change your password',
    'Open Settings > Security > Password. Enter your current password',
    'and then a new password of at least 12 characters. Pulsar',
    'enforces one uppercase, one lowercase, one digit, and one symbol.',
    'After saving, all other sessions are signed out automatically.',
    '',
    '2. Two-factor authentication',
    'Settings > Security > Two-factor authentication. Pulsar supports',
    'TOTP authenticator apps (Google Authenticator, 1Password, Authy)',
    'and hardware keys (FIDO2 / WebAuthn). Once enabled, sign-in',
    'requires both your password and a 6-digit code from your device.',
    '',
    '3. Session management',
    'Settings > Security > Active sessions lists every device and',
    'browser where you are signed in, with the IP, location, and last',
    'active time. Click Sign out to end any individual session, or',
    'Sign out everywhere to end all sessions except this one.',
    '',
    '4. API tokens',
    'Settings > Security > API tokens. Create a token with a name and',
    'scope (read-only, read-write, or admin). Pulsar shows the token',
    'value once at creation; copy and store it securely. Revoke a',
    'token at any time from the same page.',
    '',
    '5. Lost 2FA device',
    'If you lose the device that holds your 2FA codes, you can use a',
    'saved recovery code to sign in. Each member gets ten recovery',
    'codes at 2FA setup; each code works once. If you have used all',
    'of your recovery codes, contact support and a security engineer',
    'will verify your identity and reset 2FA on the workspace within',
    '1 business hour. The bot will open a security ticket for you',
    'automatically.',
    '',
    '6. IP allow-list',
    'Business and Enterprise admins can restrict workspace access',
    'to a list of IP ranges from Settings > Security > IP allow-list.',
    'Changes take effect within 5 minutes; members outside the list',
    'see a 403 error on sign-in.',
  
];
