import { describe, it, expect, vi, beforeEach } from 'vitest';

const { ingestFileMock } = vi.hoisted(() => ({ ingestFileMock: vi.fn() }));

vi.mock('../src/lib/rag/ingest', () => ({
  ingestFile: ingestFileMock,
}));

// Mock the db update that saveBlob calls after ingestion so tests
// don't need a real database connection.
const { dbUpdateMock } = vi.hoisted(() => ({ dbUpdateMock: vi.fn().mockResolvedValue(undefined) }));
vi.mock('../src/lib/db/client', () => ({
  db: { update: dbUpdateMock.mockReturnValue({ set: () => ({ where: async () => undefined }) }) },
}));
vi.mock('../src/lib/db/schema', () => ({ documents: {} }));
vi.mock('drizzle-orm', () => ({ eq: () => undefined }));

// We mock dotenv so importing the script (which calls `import 'dotenv/config'`)
// does not try to read the host's .env files.
vi.mock('dotenv/config', () => ({}));

import { runSeed, parseArgs } from './seed-docs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(HERE, 'fixtures');

// The Pulsar Analytics fixture corpus — 7 PDFs, generated by
// `scripts/make-pulsar-fixtures.ts`. Keep this list in lockstep
// with that file.
const PULSAR_FIXTURES = [
  '01-getting-started.pdf',
  '02-admin-guide.pdf',
  '03-api-reference.pdf',
  '04-billing-and-plans.pdf',
  '05-account-and-security.pdf',
  '06-troubleshooting.pdf',
  '07-data-and-integrations.pdf',
];

beforeEach(() => {
  ingestFileMock.mockReset();
});

describe('seed-docs', () => {
  it('passes every Pulsar fixture PDF to ingestFile and prints status', async () => {
    for (let i = 0; i < PULSAR_FIXTURES.length; i++) {
      ingestFileMock.mockResolvedValueOnce({
        documentId: i + 1,
        chunks: 3,
        status: 'inserted',
      });
    }

    const logs: string[] = [];
    const original = console.log;
    console.log = (...args) => logs.push(args.join(' '));
    try {
      await runSeed({ fixturesDir: FIXTURES });
    } finally {
      console.log = original;
    }

    expect(ingestFileMock).toHaveBeenCalledTimes(PULSAR_FIXTURES.length);
    const arg = ingestFileMock.mock.calls[0]?.[0] as {
      fileName: string;
      buffer: Buffer;
      uploadedBy: string;
    };
    expect(PULSAR_FIXTURES).toContain(arg.fileName);
    expect(arg.buffer.length).toBeGreaterThan(0);
    expect(arg.buffer.slice(0, 4).toString('utf8')).toBe('%PDF');
    expect(arg.uploadedBy).toBe('seed-script');
    expect(logs.join('\n')).toMatch(/01-getting-started\.pdf: status=inserted/);
  });

  it('ingests a single Pulsar fixture end-to-end through the production path', async () => {
    // One canonical fixture, three calls: insert, hash-dedup re-seed,
    // replace. Each status is reported back through `result.status`
    // and surfaced in the CLI log. This exercises the full pipeline
    // contract without actually opening a real DB connection.
    const calls: string[] = [];
    ingestFileMock.mockImplementation(async ({ fileName, buffer }: { fileName: string; buffer: Buffer }) => {
      calls.push(fileName);
      const hash = buffer.length;
      if (calls.filter((c) => c === fileName).length === 1) {
        return { documentId: 1, chunks: 3, status: 'inserted' as const, fileHash: String(hash) };
      }
      if (calls.filter((c) => c === fileName).length === 2) {
        // Same bytes → hash-dedup reports unchanged.
        return { documentId: 1, chunks: 3, status: 'unchanged' as const, fileHash: String(hash) };
      }
      return { documentId: 1, chunks: 3, status: 'updated' as const, fileHash: String(hash) };
    });
    await runSeed({ fixturesDir: join(FIXTURES, '..', 'fixtures'), userId: 'bi-test' });
    // Each fixture must have been seen at least once.
    for (const f of PULSAR_FIXTURES) {
      expect(calls).toContain(f);
    }
  });

  it('passes a custom userId when given via opts', async () => {
    for (let i = 0; i < PULSAR_FIXTURES.length; i++) {
      ingestFileMock.mockResolvedValueOnce({
        documentId: i + 1,
        chunks: 1,
        status: 'unchanged',
      });
    }
    await runSeed({ fixturesDir: FIXTURES, userId: 'admin-user-1' });
    const arg = ingestFileMock.mock.calls[0]?.[0] as { uploadedBy: string };
    expect(arg.uploadedBy).toBe('admin-user-1');
  });

  it('exits with an error when no fixtures are present', async () => {
    const errSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
    const exitSpy = vi.spyOn(process, 'exit').mockImplementation(((code?: number) => {
      throw new Error(`exit:${code}`);
    }) as never);
    await expect(
      runSeed({ fixturesDir: join(HERE, 'does-not-exist') }),
    ).rejects.toThrow('exit:1');
    expect(errSpy).toHaveBeenCalled();
    errSpy.mockRestore();
    exitSpy.mockRestore();
  });
});

describe('parseArgs', () => {
  it('defaults to ./documents when no flag is given', () => {
    expect(parseArgs([])).toEqual({ dir: './documents', userId: undefined });
  });

  it('reads --dir=VALUE', () => {
    expect(parseArgs(['--dir=./x'])).toEqual({ dir: './x', userId: undefined });
  });

  it('reads --dir VALUE (space-separated form)', () => {
    expect(parseArgs(['--dir', './x'])).toEqual({ dir: './x', userId: undefined });
  });

  it('treats a trailing --dir with no value as the default', () => {
    expect(parseArgs(['--dir'])).toEqual({ dir: './documents', userId: undefined });
  });

  it('does not consume a flag-looking value after --dir', () => {
    expect(parseArgs(['--dir', '--something'])).toEqual({
      dir: './documents',
      userId: undefined,
    });
  });

  it('captures a positional userId after --dir=VALUE', () => {
    expect(parseArgs(['--dir=./x', 'admin-1'])).toEqual({
      dir: './x',
      userId: 'admin-1',
    });
  });

  it('falls back to SEED_DOCS_DIR when --dir is absent', () => {
    const prev = process.env.SEED_DOCS_DIR;
    process.env.SEED_DOCS_DIR = './from-env';
    try {
      expect(parseArgs([])).toEqual({ dir: './from-env', userId: undefined });
    } finally {
      if (prev === undefined) delete process.env.SEED_DOCS_DIR;
      else process.env.SEED_DOCS_DIR = prev;
    }
  });
});
